import { IMAGES } from "@/assets";
import "./globals.css";
import SideBar from "@/components/SideBar";
import { Noto_Sans_JP } from "next/font/google";
import Image from "next/image";
import Provider from "./utils/provider";
import { FaCaretDown } from "react-icons/fa6";
import Header from "@/components/Header";
import { StateProvider } from "./context/stateContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const notoSans = Noto_Sans_JP({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["cyrillic"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} h-screen overflow-hidden`}>
        <StateProvider>
          {" "}
          <div className="h-screen flex overflow-hidden">
            <SideBar />
            <div className="flex-1 flex flex-col">
              <Header />
              <Provider>
                <main className="flex-1 overflow-y-auto bg-[#FBFBFF]">
                  {children}
                </main>
              </Provider>
            </div>
          </div>
        </StateProvider>
      </body>
    </html>
  );
}
